#! /bin/bash

echo start update!

DATE=`date`

git add .
git commit -m "$0 : $1 $DATE"
git push origin master
########################################
#    written by impressionyang         #
########################################
